### ISSUE TITLE
pip install numpy-ringbuffer fails with pypandoc errors

### ISSUE THREAD

**Issue by stuaxo** [eric-wieser/numpy_ringbuffer#2]
First I tried installing from scratch and got errors because pypandoc was not available, installed and tried again but still not quite there.

OS: Ubuntu 16.04
Python: 3.5

```
$ pip install numpy-ringbuffer
Collecting numpy-ringbuffer
  Downloading numpy_ringbuffer-0.2.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-9r6sqi7d/numpy-ringbuffer/setup.py", line 7, in <module>
        import pypandoc
    ImportError: No module named 'pypandoc'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9r6sqi7d/numpy-ringbuffer/setup.py", line 11, in <module>
        long_description = open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    No
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9r6sqi7d/numpy-ringbuffer/

```

```
$ pip install pypandoc
Collecting pypandoc
  Downloading pypandoc-1.3.3.tar.gz
Requirement already satisfied: setuptools in /mnt/data/home/stu/.virtualenvs/cord-py3/lib/python3.5/site-packages (from pypandoc)
Requirement already satisfied: pip>=8.1.0 in /mnt/data/home/stu/.virtualenvs/cord-py3/lib/python3.5/site-packages (from pypandoc)
Requirement already satisfied: wheel>=0.25.0 in /mnt/data/home/stu/.virtualenvs/cord-py3/lib/python3.5/site-packages (from pypandoc)
Building wheels for collected packages: pypandoc
  Running setup.py bdist_wheel for pypandoc ... done
  Stored in directory: /home/stu/.cache/pip/wheels/ae/ad/24/8ae56cccee848926ed5cb93f2d80dc3e9b6840b179d9b4936e
Successfully built pypandoc
Installing collected packages: pypandoc
Successfully installed pypandoc-1.3.3
```

```
  $ pip install numpy-ringbuffer
Collecting numpy-ringbuffer
  Using cached numpy_ringbuffer-0.2.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nb17gbac/numpy-ringbuffer/setup.py", line 8, in <module>
        long_description = pypandoc.convert('README.md', 'rst')
      File "/mnt/data/home/stu/.virtualenvs/cord-py3/lib/python3.5/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nb17gbac/numpy-ringbuffer/
```

**Comment by stuaxo** [comment]
This is a dupe of #1 my pull request should fix it.
